# Default values for tmpnotes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/soraro/tmpnotes
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

envVars:
  - name: TMPNOTES_PORT
    value: "5000"
#  - name: TMPNOTES_REDIS_URL
#    value: "redis://my-custom-redis:6379"
#  - name: TMPNOTES_ENABLE_HSTS
#    value: "true"
#  - name: TMPNOTES_MAX_EXPIRE
#    value: "24"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  privileged: false
  capabilities:
    drop: ["ALL"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
#  minReplicas: 1
#  maxReplicas: 5
#  targetCPUUtilizationPercentage: 80
#  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  enabled: true
  password: Sup3rSecretPassphrase
  persistenceEnabled: false
